#!/bin/bash
if ! command -v gh &>/dev/null; then
	echo "It appears you do not have Github CLI installed"
	echo "It is needed for this script"
	echo "It can installed from here https://cli.github.com/"
	exit 1
fi
# small script to clean up branches once PR's are done

# I void all responsibility if you bork your own shit

BRANCH=$(git branch | grep "*" | cut -d' ' -f2)


if [ "$BRANCH" != "develop" ] && [ "$BRANCH" != "prod" ]; then
    echo "---------------------"
    echo "| Merging $BRANCH.  |"
    echo "---------------------"
    git add .
    git commit -m "Automerging $BRANCH to fork develop branch"
    git push -u origin $BRANCH
    gh pr create -B develop -t "Automerger PR" --fill
    gh pr merge -d
    echo "-------------------"
    echo "| Branch cleaned. |"
    echo "-------------------"
else
    echo "--------------------"
    echo "| Updating $BRANCH! |"
    echo "--------------------"
    git pull upstream $BRANCH
    git push -u origin $BRANCH
    echo "-------------------"
    echo "| $BRANCH updated. |"
    echo "-------------------"
fi